// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MWZq5WtW_DGh2GP0Z1EE9Asw21PB3fI',
    appId: '1:395299080487:web:6e0d3666440a563cba8102',
    messagingSenderId: '395299080487',
    projectId: 'inicio-sesion-2022-d5e59',
    authDomain: 'inicio-sesion-2022-d5e59.firebaseapp.com',
    storageBucket: 'inicio-sesion-2022-d5e59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABxQCnL_JhKhCKbtsWHE-7Nh7F5rrgID0',
    appId: '1:395299080487:android:56d7610a904e5b14ba8102',
    messagingSenderId: '395299080487',
    projectId: 'inicio-sesion-2022-d5e59',
    storageBucket: 'inicio-sesion-2022-d5e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGYFIgmgMhWZHXRk9ZXU6MIKxLhLFzvOg',
    appId: '1:395299080487:ios:ca5e31737570bc71ba8102',
    messagingSenderId: '395299080487',
    projectId: 'inicio-sesion-2022-d5e59',
    storageBucket: 'inicio-sesion-2022-d5e59.appspot.com',
    iosClientId: '395299080487-mq7tiq4256938g8eel792dbof163hfrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
